#!/bin/zsh 

# Edithost
# Aplicado chave SSH
# 2021 - Steven79203 

#export EDITOR=nvim Coloque seu editor de preferência (nvim, vim nano, etc)
 export HOSTS_TMP=/tmp/hosts.tmp 	# Arquivo temporário com as mudanças
 export HOSTS=/etc/hosts 		# Arquivo original
 export PATT_TMP=/tmp/pattern.tmp 	# Padrões encontrados
 export DIFF_DIR=~/.config/hosts_diff/ 	  # Diretório dos .diffs

manual(){
	# Cópia temporária para /tmp/dothosts.tmp
	cp $HOSTS $HOSTS_TMP
	
	# Abre $HOSTS_TMP em $EDITOR
	$EDITOR $HOSTS_TMP

	# Etiqueta da modificação
	echo -n "Etiqueta da modificação (Padrão: data/hora): "; read NAME
	[[ -z $NAME ]] && NAME=$(date "+%d-%m-%y-%H-%M-%S")
	
	# Gera arquivo diff e remove tmp
	DIFF=$DIFF_DIR/dothosts_medit_$NAME.diff
	diff -u $HOSTS $HOSTS_TMP > $DIFF; rm $HOSTS_TMP

	# Descarta diff se estive vázio
	if [[ -s $DIFF ]]; then
		sudo patch $HOSTS $DIFF
	else
		rm $DIFF && echo "Não houve modificações. Saindo...";
	fi

	return 0;
}

unblock(){
	# Comenta linhas de código e desbloqueia os respectivos domínios,
	# gerando diffs que podem ser revertidos/reaplicados sem digitar o padrão novamente

	echo -n "PADRÃO: "; read PATT
	DIFF=$DIFF_DIR/dothosts_$PATT.diff
	sed "/^[^\#] *[a-zA-Z0-9\.\ ]*$PATT/ s/./#&/" $HOSTS > $PATT_TMP && diff -u $HOSTS $PATT_TMP > $DIFF

	if [[ -s $DIFF ]]; then
		bat $DIFF 
		echo -n "Aplicar modificações? [S/N]: "; read CONF;

		if [[ $CONF == 's' || $CONF == 'S' ]]; then
			sudo patch $HOSTS $DIFF 
		else
			rm $DIFF
			echo "Nada foi modificado..."
		fi
	else
		rm $DIFF
		echo "URL já desbloqueada ou padrão não encontrado. Saindo..."
		return 0;
	fi
	rm $PATT_TMP
}

undoredo(){
	#Rebloquear domínios ou bloqueiar novamente a partir dos diffs antigos. 

	# Verificando a presença de arquivos diff
	MSG="Undo - Reverte patches\nRedo - Reaplica patches previamente feitos\n:"
	echo -n -e $MSG; read OPR

	case $OPR in 
		'undo') SUFFIXO="diff";SUFFIXN="diff.old";ARG=-R ;;
		'redo') SUFFIXO="diff.old";SUFFIXN="diff";ARG='';;
		*) return 0;
	esac

	[[ $(getFilesList "$SUFFIXO" | wc -l) == 0 ]] && echo "Sem histórico de modificações. Saindo..." && return 0;

	while true; do	
		DIFF=$( getFilesList "$SUFFIXO" | dmenu -l 10 -p "Qual patch reverter?"); [[ -z $DIFF ]] && return 0;
		RDIFF=$DIFF_DIR/$DIFF
		bat $RDIFF
		
		echo -n "Aplicar mudanças? [S/N]: "; read CONF
		
		if [[ $CONF == 's' || $CONF == 'S' ]]; then
			sudo patch $ARG $HOSTS $RDIFF 
			mv $RDIFF ${RDIFF%${SUFFIXO}}$SUFFIXN
		else
			continue;
		fi
	done
}

getFilesList(){
	ls $DIFF_DIR | grep "$1$"
}

# Verifica se o diretório hosts_diff existe. Caso contrário cria um em ~/.config/hosts_diff

[[ -e $DIFF_DIR ]] || mkdir $DIFF_DIR

OP=$(echo -e "Edição Manual\nDesbloquear Domínios\nReverter/Reaplicar Patches" | dmenu -p "Operação: ")

case $OP in
	'Edição Manual') manual ;; 
	'Desbloquear Domínios') unblock ;;
	'Reverter/Reaplicar Patches') undoredo ;;
	*) return 0;
esac

